---
title: "MS_Osteosarcoma_CHROMVAR_integrate_RNAseq_DEGs_ATACseq_DARs"
author: "XuanThangNguyen"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---



```{r set up, include=FALSE}
# library(BiocManager)
# options(timeout = 5200) 
# BiocManager::install(c("chromVAR", "motifmatchr", BSgenome.Hsapiens.UCSC.hg19", 
#                         "BSgenome.Hsapiens.UCSC.hg38", "JASPAR2016", "JASPAR2022"))

set.seed(1012)

# Set directory paths
root_dir <- rprojroot::find_root(rprojroot::has_dir("OS_ATACseq_RUNX2i"))
analysis_dir <- file.path(root_dir, "OS_ATACseq_RUNX2i")
plots_dir <- file.path(analysis_dir, "DMSO_MACS2_ChromVAR")
# Create plots_dir if it doesn't exist
if (!dir.exists(plots_dir)) {
  dir.create(plots_dir, recursive = TRUE)
}
# library(DiffBind)
library(dplyr)
library(ggplot2)
library(chromVAR)
library(SummarizedExperiment)
library(motifmatchr)
library(BSgenome.Hsapiens.UCSC.hg38)
library(Matrix)
library(tidyverse)
library(JASPAR2022)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
```




```{r}
# Load peak file
ATAC_peaks <- read.table(file.path(analysis_dir, "featureCounts/bedfiles_DMSO", "OS_ATACseq_MACS2_merged_peaks.bed"), header=FALSE)
# Create a GRanges object from merged_peaks.bed
colnames(ATAC_peaks) <- c("chr", "start", "end")
ATAC_peaks <- GRanges(seqnames=ATAC_peaks$chr, 
                      ranges=IRanges(start=ATAC_peaks$start,
                                     end=ATAC_peaks$end))

library(ChIPpeakAnno)
library(ChIPseeker)
bed.annot = annotatePeak(ATAC_peaks, 
                         tssRegion=c(-1000, 1000),
                         TxDb=TxDb.Hsapiens.UCSC.hg38.knownGene, 
                         annoDb="org.Hs.eg.db")

ATAC_annot_peaks <- as.data.frame(bed.annot)
colnames(ATAC_annot_peaks)
library(openxlsx)
write.xlsx(ATAC_annot_peaks, file=file.path(plots_dir, "ATAC_annot_peaks.xlsx"))

# Load peak counts
ATAC_raw_counts <- read.delim(file.path(analysis_dir, "featureCounts/bedfiles_DMSO", "OS_ATACseq_MACS2_peak_counts.txt"), comment.char="#", row.names=1)
# Confirm the peaks and data are overlap
nrow(ATAC_peaks)
nrow(ATAC_raw_counts)
head(ATAC_peaks)
head(ATAC_raw_counts)
# modify the colnames and 
colnames(ATAC_raw_counts) <- gsub(pattern = "X\\.|_hg38_final\\.bam", replacement = "", x = colnames(ATAC_raw_counts))
# coordinate ID in raw counts
ATAC_raw_counts$peakID <- paste(ATAC_raw_counts$Chr, ATAC_raw_counts$Start, ATAC_raw_counts$End, sep="_")
# Add peakID as rownames
rownames(ATAC_raw_counts) <- ATAC_raw_counts$peakID
# coordinate ID in annotation
ATAC_annot_peaks$peakID <- paste(ATAC_annot_peaks$seqnames, ATAC_annot_peaks$start, ATAC_annot_peaks$end, sep="_")
ATAC_raw_counts_merged_peaks <- merge(
  ATAC_raw_counts,
  ATAC_annot_peaks[, c("peakID", "annotation", "distanceToTSS", "SYMBOL", "GENENAME")],
  by="peakID",
  all.x=TRUE)

```


```{r}


# Filter only DMSO data
ATAC_counts <- ATAC_raw_counts[ ,  grep("DMSO_rep", colnames(ATAC_raw_counts))]
colnames(ATAC_counts) <- gsub(pattern = "DMSO_rep", replacement = "", x = colnames(ATAC_counts))
head(ATAC_counts)

# Generate experimental design
library(dplyr)
library(stringr)
experiment_design <- data.frame(sample = colnames(ATAC_counts)) %>%
  tidyr::separate(sample, into = c("cell", "replicate"), sep = "_", remove = FALSE) %>%
  mutate(replicate = paste0("rep", replicate),
         condition = ifelse(cell == "MG63",  "Low_Aggressive", "High_Aggressive"))

# chromVAR input
ATAC_chromVAR <- SummarizedExperiment(assays = list(counts = as.matrix(ATAC_counts)),
                                      rowRanges = ATAC_peaks,
                                      colData = experiment_design)
# Inspect raw counts
raw_counts <- assays(ATAC_chromVAR)$counts
# Filter out peaks with zero total counts across all samples
keep_peaks <- rowSums(raw_counts) > 10
ATAC_chromVAR <- ATAC_chromVAR[keep_peaks, ]

# Add GC bias
ATAC_chromVAR <- addGCBias(ATAC_chromVAR,
                     genome = BSgenome.Hsapiens.UCSC.hg38)

# Check your SummarizedExperiment object
ATAC_chromVAR

# Load motifs (JASPAR)
motifs <- getJasparMotifs(species = "Homo sapiens", collection = "CORE")
# Match motif of peaks to
motif_ix <- matchMotifs(motifs, ATAC_chromVAR, 
                        genome = BSgenome.Hsapiens.UCSC.hg38)

# Now run computeDeviations
ATAC_chromVAR_motif <- computeDeviations(object = ATAC_chromVAR, annotations = motif_ix)

save(ATAC_chromVAR_motif, file = file.path(plots_dir, "ATAC_chromVAR_MACS2_motif.rda"))

```

```{r VARIETY, CLUSTERING}
load(file.path(plots_dir, "ATAC_chromVAR_MACS2_motif.rda"))

sample_cor <- getSampleCorrelation(ATAC_chromVAR_motif)
library(pheatmap)
pdf("ATAC_chromVAR_TF_Motif_Activity_corelation.pdf", width = 4, height = 3.5)
pheatmap(sample_cor,
         clustering_distance_rows = as.dist(1 - sample_cor),
         clustering_distance_cols = as.dist(1 - sample_cor),
         color = colorRampPalette(c("white", "#4d9221"))(100))
dev.off()
# compute variability on chromVAR object, not matrix
variability <- computeVariability(ATAC_chromVAR_motif)
# MG63_variability <- computeVariability(ATAC_chromVAR_motif)
# U2OS_variability <- computeVariability(ATAC_chromVAR_motif)
# HOS_variability <- computeVariability(ATAC_chromVAR_motif)

plotVariability(variability,
                xlab = "Rank of TFs",
                n = 50,
                use_plotly = FALSE) 
ggsave("OS_Rank_TF_Motif_Activity.pdf", width = 5, height = 4)
# ggsave("U2OS_Rank_TF_Motif_Activity.pdf", width = 5, height = 4)
# ggsave("HOS_Rank_TF_Motif_Activity.pdf", width = 5, height = 4)
# ggsave("MG63_Rank_TF_Motif_Activity.pdf", width = 5, height = 4)

# Convert to data frame
# variability_df <- as.data.frame(MG63_variability)
# variability_df <- as.data.frame(U2OS_variability)
# variability_df <- as.data.frame(HOS_variability)
variability_df <- as.data.frame(variability)
# Add catTFRE data
U2OS_catTFRE_RNAseq <- read.xlsx("Results_FINAL_RAW/U2OS_catTFRE_RNAseq.xlsx")
HOS_catTFRE_RNAseq <- read.xlsx("Results_FINAL_RAW/HOS_catTFRE_RNAseq.xlsx")

variability_df <- variability_df %>% 
  left_join(U2OS_catTFRE_RNAseq[,c("Gene", "Expression_catTFRE", "expression_group_label")], by = c("name"="Gene")) %>%
  dplyr::rename(U2OS_catTFRE_RNAseq = expression_group_label,
                U2OS_catTFRE = Expression_catTFRE)
variability_df <- variability_df %>% 
  left_join(HOS_catTFRE_RNAseq[,c("Gene", "Expression_catTFRE", "expression_group_label")], by = c("name"="Gene")) %>%
  dplyr::rename(HOS_catTFRE_RNAseq = expression_group_label,
                HOS_catTFRE = Expression_catTFRE)
```

```{r}
library(dplyr)
library(forcats)
library(ggplot2)
library(tidyr)   # for replace_na()
colnames(df)
# 1) Rank and order gene names by variability (desc)
df <- variability_df %>%
  as.data.frame() %>%
  dplyr::arrange(dplyr::desc(variability)) %>%
  dplyr::mutate(rank = dplyr::row_number(),
                U2OS_catTFRE = tidyr::replace_na(U2OS_catTFRE, "NA"),
                U2OS_catTFRE_RNAseq = tidyr::replace_na(U2OS_catTFRE_RNAseq, "NA"),
                HOS_catTFRE = tidyr::replace_na(HOS_catTFRE, "NA"),
                HOS_catTFRE_RNAseq = tidyr::replace_na(HOS_catTFRE_RNAseq, "NA"),
                topUP = dplyr::case_when(U2OS_catTFRE %in% c("Downregulated","Upregulated")  ~ "Significant",
                                         HOS_catTFRE %in% c("Downregulated","Upregulated")  ~ "Significant",
                                         U2OS_catTFRE == "Not_significant"           ~ "Not_significant",
                                         HOS_catTFRE  == "Not_significant"           ~ "Not_significant",
                                         TRUE                                        ~ "Not_detected" ),
                name = forcats::fct_reorder(name, variability, .desc = TRUE))

# Define TFs you want to label
label_list <- c("RUNX2", "EGR1", "MYBL2",  "JUND", "FOSL2", "JUNB", "NFIA", "NFIB", # Significant
                "TEAD1", "TEAD3", "TEAD4", "FOXO3","NFYB", "STAT3", "RUNX3", "TP53")  #Not Significant
# c(MG63="#4d9221", U2OS="#e9a3c9", HOS="#c51b7d",
# c(MG63="#ff7f00", U2OS="#56B4E9", HOS="#4daf4a",
library(ggrepel)
library(grid)   # for unit()
# count TFs per group
counts <- df %>% dplyr::count(topUP)
# build a named vector for legend labels
labels_with_counts <- paste0(counts$topUP, " (n=", counts$n, ")")
names(labels_with_counts) <- counts$topUP
# Plot with ggplot2
ggplot(df, aes(x = rank, y = variability, color = topUP)) +
  geom_point(size = 2) +
  scale_color_manual(
    values = c(Not_significant="#56B4E9", Significant ="magenta", Not_detected ="grey"),
    labels = labels_with_counts) +
  ggrepel::geom_label_repel(
    data = df %>% dplyr::filter(name %in% label_list),
    aes(label = name, color = topUP),
    size = 3,
    fill = "white",
    label.size = 0.25,
    label.padding = unit(0.15, "lines"),
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "grey",
    segment.size = 0.3,
    max.overlaps = Inf,
    show.legend = FALSE) +        # << prevent labels from influencing legend 
  labs(x = "Rank of TFs", y = "Variability", color = "topUp_in_catTFRE") +
  theme_bw() +
  theme(panel.grid.minor = element_blank()) +
  guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))
ggsave(filename = file.path(plots_dir, "TF_Motif_classification_OS_ATAC_sample.pdf"), height = 4, width = 5)
```



```{r Heat map and comparision}
# Get TF activity deviation z-scores
dev <- deviationScores(ATAC_chromVAR_motif)
# Get TF activity deviation z-scores
dev_matrix <- as.matrix(dev)  # rows: TF motifs, columns: samples
# Scale row-wise (i.e., each TF motif across samples)
z_matrix <- t(apply(dev_matrix, 1, 
                       function(x){ (x - mean(x)) / sd(x)}))

# Define desired sample order
desired_order <- c("MG63_1", "MG63_2", "U2OS_1", "U2OS_2", "HOS_1", "HOS_2")

# Match colnames and set factor levels
sample_groups <- data.frame(Group = factor(desired_order, levels = desired_order))
rownames(sample_groups) <- desired_order

# Reorder z_matrix
z_matrix_ordered <- z_matrix[, desired_order, drop = FALSE]
sample_groups_ordered <- sample_groups[desired_order, , drop = FALSE]

library(pheatmap)
pdf(file = file.path(plots_dir,"CHROMVAR_DMSO_heatmap.pdf"), height = 40, width = 10)
pheatmap(z_matrix_ordered,
         #annotation_col = sample_groups_ordered,
         cluster_cols = FALSE,
         cluster_rows = TRUE)
dev.off()


# Compare between cell lines
library(limma)
# Design matrix with proper sample names
## 2) Build group factor from column names (robust to order)
cell <- sub("_\\d+$", "", colnames(dev))          # "HOS_1" -> "HOS"
group <- factor(cell, levels = c("HOS","MG63","U2OS"))  # control ordering if desired
## 3) Design & fit
design <- model.matrix(~ 0 + group)               # columns: HOS, MG63, U2OS
colnames(design) <- levels(group)
rownames(design) <- colnames(dev)
stopifnot(all(colnames(dev) == rownames(design)))  # sanity check
# 4) Now this will work because dev = motifs × samples
fit <- lmFit(dev, design)

# 5) Prepare the contrast HOS-MG63
contrast_HOSMG63 <- makeContrasts(HOSminusMG63 = HOS - MG63, levels = design)
fit2 <- contrasts.fit(fit, contrast_HOSMG63)
fit2 <- eBayes(fit2, robust = TRUE)               # robust often helps with outliers)

# View top TF motifs differentially active
topTFs_HOS_MG63 <- topTable(fit2, number = Inf) %>%
  rownames_to_column("TF") %>%
  mutate(Significant = P.Value < 0.05,
         SYMBOL=str_replace(TF, ".*_", ""))
head(topTFs_HOS_MG63)
write.xlsx(topTFs_HOS_MG63, file=file.path("topTFs_HOS_MG63_Differential_TF_Motif_Activity.xlsx"))

# 5) Prepare the contrast U2OS-MG63
contrast_U2OSMG63 <- makeContrasts(U2OSminusMG63 = U2OS - MG63, levels = design) # RUNX2
fit3 <- contrasts.fit(fit, contrast_U2OSMG63)
fit3 <- eBayes(fit3, robust = TRUE)               # robust often helps with outliers)

# View top TF motifs differentially active
topTFs_U2OS_MG63 <- topTable(fit3, number = Inf) %>%
  rownames_to_column("TF") %>%
  mutate(Significant = P.Value < 0.05,
         SYMBOL=str_replace(TF, ".*_", ""))
head(topTFs_U2OS_MG63)
write.xlsx(topTFs_U2OS_MG63, file=file.path("topTFs_U2OS_MG63_Differential_TF_Motif_Activity.xlsx"))

```


```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)

# DEG MS
U2OS_catTFRE_RNAseq <- read.xlsx("Results_FINAL_RAW/U2OS_catTFRE_RNAseq.xlsx")
HOS_catTFRE_RNAseq <- read.xlsx("Results_FINAL_RAW/HOS_catTFRE_RNAseq.xlsx")

topTFs_U2OS_MG63_df <- topTFs_U2OS_MG63 %>% 
  left_join(U2OS_catTFRE_RNAseq[,c("Gene", "Expression_catTFRE", "expression_group_label")], by = c("SYMBOL"="Gene")) %>%
  dplyr::rename(U2OS_catTFRE_RNAseq = expression_group_label,
                U2OS_catTFRE = Expression_catTFRE) %>%
  dplyr::mutate(U2OS_catTFRE = tidyr::replace_na(U2OS_catTFRE, "NA"),
                U2OS_catTFRE_RNAseq = tidyr::replace_na(U2OS_catTFRE_RNAseq, "NA"),
                topUP = dplyr::case_when(U2OS_catTFRE == "Downregulated"  ~ "MG63",
                                         U2OS_catTFRE == "Upregulated"    ~ "U2OS",
                                         TRUE                             ~ "Other" ),
                sig = adj.P.Val < 0.05 & abs(logFC) > 1, # significance threshold (use adj.P.Val if you prefer)
                sig_group = case_when(sig & logFC > 0  ~ "U2OS_up",
                                      sig & logFC < 0  ~ "MG63_up",
                                      TRUE             ~ "Not_significant"), # group by direction + significance
                mlog10p = -log10(P.Value))
# 2) Choose genes to label
label_genes <- c("NFIA", "ZEB1", "FOXC1", "NFIX", "JUND", "JUNB",
                 "RUNX2", "POU2F1","ETV6", "EGR1", "ETV6")   # <- edit this list
lab_df <- topTFs_U2OS_MG63_df %>%  dplyr::filter(SYMBOL %in% label_genes)

# 3) Colors (Okabe–Ito; colorblind-safe)
cols <- c(U2OS_up         = "#F66239",  # sky blue
          MG63_up         = "#56B4E9",  # bluish green
          Not_significant = "grey80") 
# 4) Plot
# counts for sig_group legend
counts_sig <- topTFs_U2OS_MG63_df %>% dplyr::count(sig_group)
labels_sig <- paste0(counts_sig$sig_group, " (n=", counts_sig$n, ")")
names(labels_sig) <- counts_sig$sig_group
# counts for topUP overlap legend
counts_topup <- topTFs_U2OS_MG63_df %>%
  dplyr::filter(!is.na(topUP) & topUP != "Other") %>%
  dplyr::count(topUP)
labels_topup <- paste0(counts_topup$topUP, " (n=", counts_topup$n, ")")
names(labels_topup) <- counts_topup$topUP
# Plot
ggplot(topTFs_U2OS_MG63_df, aes(x = logFC, y = mlog10p)) +
  geom_point(aes(color = sig_group), alpha = 0.9, size = 2) +
  scale_color_manual(values = cols, name = "Direction", labels = labels_sig) +
  geom_point(aes(shape = topUP),
             data = subset(topTFs_U2OS_MG63_df, !is.na(topUP) & topUP != "Other"),
             color = "magenta", fill = NA, size = 2.8, stroke = 1) +
  scale_shape_manual(values = c(MG63 = 21, HOS = 21, U2OS = 21),
                     name   = "catTFRE overlap",
                     labels = labels_topup) +
  geom_label_repel(data = lab_df,
                   aes(label = TF, color = sig_group),
                   fill = "white", label.size = 0.25, size = 3,
                   box.padding = 0.4, point.padding = 0.5, 
                   min.segment.length = 0,
                   max.overlaps = Inf, show.legend = FALSE) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  labs(title = "Volcano Plot of Differential TF Motif Activity",
       x = "log2 Fold Change (U2OS vs MG63)",
       y = "-log10(P-value)") +
  theme_minimal(base_size = 14) +
  guides(color = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(color = "magenta", fill = NA, size = 4)))
ggsave("Volcano_Plot_U2OS_MG63_Differential_TF_Motif_Activity_catTFRE_RNA.pdf", width = 7, height = 4)

##############################################################################################################################
# 1) Prep: define significance & direction groups
topTFs_HOS_MG63_df <- topTFs_HOS_MG63 %>% 
  left_join(HOS_catTFRE_RNAseq[,c("Gene", "Expression_catTFRE", "expression_group_label")], by = c("SYMBOL"="Gene")) %>%
  dplyr::rename(HOS_catTFRE_RNAseq = expression_group_label,
                HOS_catTFRE = Expression_catTFRE) %>%
  dplyr::mutate(HOS_catTFRE = tidyr::replace_na(HOS_catTFRE, "NA"),
                HOS_catTFRE_RNAseq = tidyr::replace_na(HOS_catTFRE_RNAseq, "NA"),
                topUP = dplyr::case_when(HOS_catTFRE == "Downregulated"  ~ "MG63",
                                         HOS_catTFRE == "Upregulated"    ~ "HOS",
                                         TRUE                             ~ "Other" ), 
                sig = adj.P.Val < 0.05 & abs(logFC) > 1, # significance threshold (use adj.P.Val if you prefer)
                sig_group = case_when(sig & logFC > 0  ~ "HOS_up",
                                      sig & logFC < 0  ~ "MG63_up",
                                      TRUE             ~ "Not_significant"), # group by direction + significance
                mlog10p = -log10(P.Value))
# 2) Choose genes to label
label_genes <- c("NFIA", "ZEB1", "FOXC1", "NFIX", "JUND", "JUNB",
                 "RUNX2", "POU2F1","ETV6", "EGR1", "ETV6")   # <- edit this list
lab_df <- topTFs_HOS_MG63_df %>%  dplyr::filter(SYMBOL %in% label_genes)
# 3) Colors (Okabe–Ito; colorblind-safe)
cols <- c(HOS_up         = "#8332FF",  
          MG63_up         = "#56B4E9",
          Not_significant = "grey80")
# 4) Plot
# counts for sig_group legend
counts_sig <- topTFs_HOS_MG63_df %>% dplyr::count(sig_group)
labels_sig <- paste0(counts_sig$sig_group, " (n=", counts_sig$n, ")")
names(labels_sig) <- counts_sig$sig_group

# counts for topUP overlap legend
counts_topup <- topTFs_HOS_MG63_df %>%
  dplyr::filter(!is.na(topUP) & topUP != "Other") %>%
  dplyr::count(topUP)
labels_topup <- paste0(counts_topup$topUP, " (n=", counts_topup$n, ")")
names(labels_topup) <- counts_topup$topUP

ggplot(topTFs_HOS_MG63_df, aes(x = logFC, y = mlog10p)) +
  geom_point(aes(color = sig_group), alpha = 0.9, size = 2) +
  scale_color_manual(values = cols, name = "Direction", labels = labels_sig) +
  geom_point(aes(shape = topUP),
             data = subset(topTFs_HOS_MG63_df, !is.na(topUP) & topUP != "Other"),
             color = "magenta", fill = NA, size = 2.8, stroke = 1) +
  scale_shape_manual(values = c(MG63 = 21, HOS = 21, U2OS = 21),
                     name   = "catTFRE overlap",
                     labels = labels_topup) +
  geom_label_repel(data = lab_df,
                   aes(label = TF, color = sig_group),
                   fill = "white", label.size = 0.25, size = 3,
                   box.padding = 0.4, point.padding = 0.5, 
                   min.segment.length = 0,
                   max.overlaps = Inf, show.legend = FALSE) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  labs(title = "Volcano Plot of Differential TF Motif Activity",
       x = "log2 Fold Change (HOS vs MG63)",
       y = "-log10(P-value)") +
  theme_minimal(base_size = 14) +
  guides(color = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(color = "magenta", fill = NA, size = 4)))
ggsave("Volcano_Plot_HOS_MG63_Differential_TF_Motif_Activity_catTFRE_RNA.pdf", width = 7, height = 4)
```


```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)

# DEG MS
catTFRE_U2OS_MG63 <- read.xlsx("DEP_Plots_C1_threshold0/Diffenrential_Protein_Expression_U2OS_vs_MG63.xlsx")
catTFRE_HOS_MG63 <- read.xlsx("DEP_Plots_C1_threshold0/Diffenrential_Protein_Expression_HOS_vs_MG63.xlsx")

topTFs_U2OS_MG63_df <- topTFs_U2OS_MG63 %>% 
  left_join(catTFRE_U2OS_MG63[,c("protein", "Expression")], by = c("SYMBOL"="protein")) %>%
  dplyr::rename(U2OS_catTFRE = Expression) %>%
  dplyr::mutate(U2OS_catTFRE = tidyr::replace_na(U2OS_catTFRE, "NA"),
                topUP = dplyr::case_when(U2OS_catTFRE %in% c("Downregulated", "Not_significant","Upregulated")  ~ "catTFRE",
                                         TRUE                                        ~ "Not_detected" ),
                sig = adj.P.Val < 0.05 & abs(logFC) > 1, # significance threshold (use adj.P.Val if you prefer)
                sig_group = case_when(sig & logFC > 0  ~ "U2OS_up",
                                      sig & logFC < 0  ~ "MG63_up",
                                      TRUE             ~ "Not_significant"), # group by direction + significance
                mlog10p = -log10(P.Value))
# 2) Choose genes to label
label_genes <- c("NFIA", "ZEB1", "FOXC1", "NFIX", "JUND", "JUNB",
                 "RUNX2", "POU2F1","ETV6", "EGR1", "ETV6")   # <- edit this list
lab_df <- topTFs_U2OS_MG63_df %>% dplyr::filter(SYMBOL %in% label_genes)

# 3) Colors (Okabe–Ito; colorblind-safe)
cols <- c(U2OS_up         = "#F66239",  # sky blue
          MG63_up         = "#56B4E9",  # bluish green
          Not_significant = "grey80") 
# 4) Plot
# counts for sig_group legend
counts_sig <- topTFs_U2OS_MG63_df %>% dplyr::count(sig_group)
labels_sig <- paste0(counts_sig$sig_group, " (n=", counts_sig$n, ")")
names(labels_sig) <- counts_sig$sig_group
# counts for topUP overlap legend
counts_topup <- topTFs_U2OS_MG63_df %>%
  dplyr::filter(!is.na(topUP) & topUP != "Other") %>%
  dplyr::count(topUP)
labels_topup <- paste0(counts_topup$topUP, " (n=", counts_topup$n, ")")
names(labels_topup) <- counts_topup$topUP
# Plot
ggplot(topTFs_U2OS_MG63_df, aes(x = logFC, y = mlog10p)) +
  geom_point(aes(color = sig_group), alpha = 0.9, size = 2) +
  scale_color_manual(values = cols, name = "Direction", labels = labels_sig) +
  geom_point(aes(shape = topUP),
             data = subset(topTFs_U2OS_MG63_df, !is.na(topUP) & topUP != "Not_detected"),
             color = "magenta", fill = NA, size = 2.8, stroke = 1) +
  scale_shape_manual(values = c(catTFRE = 21),
                     name   = "catTFRE overlap",
                     labels = labels_topup) +
  geom_label_repel(data = lab_df,
                   aes(label = TF, color = sig_group),
                   fill = "white", label.size = 0.25, size = 3,
                   box.padding = 0.4, point.padding = 0.5, 
                   min.segment.length = 0,
                   max.overlaps = Inf, show.legend = FALSE) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  labs(title = "Volcano Plot of Differential TF Motif Activity",
       x = "log2 Fold Change (U2OS vs MG63)",
       y = "-log10(P-value)") +
  theme_minimal(base_size = 14) +
  guides(color = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(color = "magenta", fill = NA, size = 4)))
ggsave("Volcano_Plot_U2OS_MG63_Differential_TF_Motif_Activity_ALLcatTFRE.pdf", width = 7, height = 4)

##############################################################################################################################
# 1) Prep: define significance & direction groups
topTFs_HOS_MG63_df <- topTFs_HOS_MG63 %>% 
  left_join(HOS_catTFRE_RNAseq[,c("Gene", "Expression_catTFRE", "expression_group_label")], by = c("SYMBOL"="Gene")) %>%
  dplyr::rename(HOS_catTFRE_RNAseq = expression_group_label,
                HOS_catTFRE = Expression_catTFRE) %>%
  dplyr::mutate(HOS_catTFRE = tidyr::replace_na(HOS_catTFRE, "NA"),
                topUP = dplyr::case_when(HOS_catTFRE %in% c("Downregulated", "Not_significant","Upregulated")  ~ "catTFRE",
                                         TRUE                                        ~ "Not_detected" ),
                sig = adj.P.Val < 0.05 & abs(logFC) > 1, # significance threshold (use adj.P.Val if you prefer)
                sig_group = case_when(sig & logFC > 0  ~ "HOS_up",
                                      sig & logFC < 0  ~ "MG63_up",
                                      TRUE             ~ "Not_significant"), # group by direction + significance
                mlog10p = -log10(P.Value))
# 2) Choose genes to label
label_genes <- c("NFIA", "ZEB1", "NFIX", "JUND", "JUNB", "JUN",
                 "RUNX2", "FOXC2", "MEIS2", "EGR1", "MEIS2" )   # <- edit this list
lab_df <- topTFs_HOS_MG63_df %>% dplyr::filter(SYMBOL %in% label_genes)
# 3) Colors (Okabe–Ito; colorblind-safe)
cols <- c(HOS_up         = "#8332FF",  
          MG63_up         = "#56B4E9",
          Not_significant = "grey80")
# 4) Plot
# counts for sig_group legend
counts_sig <- topTFs_HOS_MG63_df %>% dplyr::count(sig_group)
labels_sig <- paste0(counts_sig$sig_group, " (n=", counts_sig$n, ")")
names(labels_sig) <- counts_sig$sig_group

# counts for topUP overlap legend
counts_topup <- topTFs_HOS_MG63_df %>%
  dplyr::filter(!is.na(topUP) & topUP != "Other") %>%
  dplyr::count(topUP)
labels_topup <- paste0(counts_topup$topUP, " (n=", counts_topup$n, ")")
names(labels_topup) <- counts_topup$topUP

ggplot(topTFs_HOS_MG63_df, aes(x = logFC, y = mlog10p)) +
  geom_point(aes(color = sig_group), alpha = 0.9, size = 2) +
  scale_color_manual(values = cols, name = "Direction", labels = labels_sig) +
  geom_point(aes(shape = topUP),
             data = subset(topTFs_HOS_MG63_df, !is.na(topUP) & topUP != "Other"),
             color = "magenta", fill = NA, size = 2.8, stroke = 1) +
  scale_shape_manual(values = c(catTFRE = 21),
                     name   = "catTFRE overlap",
                     labels = labels_topup) +
  geom_label_repel(data = lab_df,
                   aes(label = TF, color = sig_group),
                   fill = "white", label.size = 0.25, size = 3,
                   box.padding = 0.4, point.padding = 0.5, 
                   min.segment.length = 0,
                   max.overlaps = Inf, show.legend = FALSE) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  labs(title = "Volcano Plot of Differential TF Motif Activity",
       x = "log2 Fold Change (HOS vs MG63)",
       y = "-log10(P-value)") +
  theme_minimal(base_size = 14) +
  guides(color = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(color = "magenta", fill = NA, size = 4)))
ggsave("Volcano_Plot_HOS_MG63_Differential_TF_Motif_Activity_ALLcatTFRE.pdf", width = 7, height = 4)
```



```{r Cell / sample similarity}

tsne_results <- deviationsTsne(ATAC_chromVAR_motif, threshold = 1.5, perplexity = 10, 
                               shiny = FALSE)

head(tsne_results)
colData(ATAC_chromVAR_motif)
# Example: derive subtype from sample names
subtypes <- gsub("_PT[0-9]+", "", colnames(deviationScores(ATAC_chromVAR_motif)))
colData(ATAC_chromVAR_motif)$Subtype <- subtypes
head(colData(ATAC_chromVAR_motif)$Subtype)

tsne_plot <- plotDeviationsTsne(ATAC_chromVAR_motif, tsne_results,
                                 sample_column = "Subtype",  # must exist in colData(ATAC_chromVAR_motif)
                                 shiny = FALSE)
grep("RUNX2", rownames(deviationScores(ATAC_chromVAR_motif)), value = TRUE)
# Might return "MA0511.2_RUNX2"

tsne_plots <- plotDeviationsTsne(ATAC_chromVAR_motif, tsne_results,
                                 sample_column = "Subtype",
                                 shiny = FALSE)
print(tsne_plots)

tsne_plots <- plotDeviationsTsne(
  object = ATAC_chromVAR_motif,
  tsne = tsne_results,
  annotation = "FOS",             # or "MA0511.2_RUNX2" depending on motif name
  sample_column = "Subtype",
  shiny = FALSE)
# View both
tsne_plots[[1]]  # color by subtype
tsne_plots[[2]]  # color by TF deviation (e.g., RUNX2)

# ggsave("tsne_plot_by_subtype.pdf", tsne_plot, width = 8, height = 6)

```






```{r, DESeq2 and PCA}
ATAC_DEseq2_normalized = data.frame(counts(ATAC_DEseq2_dds, normalized=TRUE))
rownames(ATAC_DEseq2_normalized) = paste0(ATAC_raw_counts$Chr, '_', ATAC_raw_counts$Start, '_', ATAC_raw_counts$End)

library(reshape2)
lf = melt(ATAC_DEseq2_normalized, id.vars=c())
ggplot(data=lf, aes(x=variable, y=value)) + 
  geom_boxplot(aes(group=variable)) + 
  xlab("Sample") + ylab("Normalized Count") + 
  coord_flip()

ggplot(data=lf, aes(x=value)) + 
  geom_freqpoly(aes(group=variable, color=variable), bins=30) + 
  xlab("Sample") + ylab("Normalized Count")

libsize = data.frame(x=sizeFactors(ATAC_DEseq2_dds), y=colSums(assay(ATAC_DEseq2_dds)))
ggplot(data=libsize, aes(x=x, y=y)) + geom_point() + geom_smooth(method="lm") + xlab("Estimated size factor") + ylab("Library size")

# Principal component analysis (PCA Normalized data)
pca = prcomp(t(ATAC_DEseq2_normalized))
print(summary(pca))

library(ggplot2)
library(ggrepel)  # for better label placement

pcaData <- merge(
  as.data.frame(pca$x) %>% tibble::rownames_to_column("sample"),
  experiment_design)

ggplot(
  data = pcaData,
  aes(
    x = PC1, y = PC2,
    color = cell,
    label = sample)) +
  geom_point(size = 3) +
  geom_text_repel(size = 3, max.overlaps = 15) +
  xlab(paste0("PC1: ", round(100 * (pca$sdev[1]^2 / sum(pca$sdev^2)), 1), "% variance")) +
  ylab(paste0("PC2: ", round(100 * (pca$sdev[2]^2 / sum(pca$sdev^2)), 1), "% variance")) +
  theme_minimal()
ggsave(filename=file.path(plots_dir, "DESeq_PCA_normalized.pdf"), width = 6, height = 5, dpi = 600)
```
