---
title: "Untitled"
author: "XuanThangNguyen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# BiocManager::install("DESeq2")

#Loading Package 
library("SummarizedExperiment")
library("DEP")
library("dplyr")
library("DESeq2")
library("tidyverse")
library("openxlsx")
library("limma")
library("WGCNA")
allowWGCNAThreads() 
root_dir <- rprojroot::find_root(rprojroot::has_dir("catTFRE_MS_FinalRound"))
analysis_dir <- file.path(root_dir, "catTFRE_MS_FinalRound/WGCNA")
plots_dir <- file.path(analysis_dir, "catTFRE_C1")

# Create directories if they don't exist
if (!dir.exists(plots_dir)) {
  dir.create(plots_dir, recursive = TRUE)
}
if (!dir.exists(analysis_dir)) {
  dir.create(analysis_dir, recursive = TRUE)
}

# https://bioinformaticsworkbook.org/tutorials/wgcna.html#gsc.tab=0

set.seed(1234)
```


##1. Load Osteosarcoma catTFRE data
```{r data loading}
# 1.1 Import the data
# Load the data
# catTFRE_MS_Round4 <- read.xlsx("catTRFR_MS_Round4_MG63_U2OS_HOS_sumC1C4.xlsx", rowNames = F)
# colnames(catTRFE_MS_Round4)

# Human TFs list of Transcription Factor (TFs) were generated by merging the list TFs between: 
# Human TFs list of Human Protein Atlas database: https://www.proteinatlas.org/search/transcription+factor
# Human TFs list of AnimalTFDB: # http://bioinfo.life.hust.edu.cn/AnimalTFDB/#!/download
# Human TFs list of Human Transcription Factors network 2018: # https://doi.org/10.1016/j.cell.2018.01.029
# Human TFs list of Uniprot database: https://www.uniprot.org/uniprotkb?facets=model_organism%3A9606%2Cexistence%3A2&query=transcription%20factor 
# Human TFs list of GeneCards database: https://www.genecards.org/Search/Keyword?queryString=%22human%20transcription%20factor%22
# Human Epifactor gene list: https://epifactors.autosome.org/description

# Import Transcription factor list
TFs_list <- read.xlsx(file.path(analysis_dir ,"TFs_list_Final.xlsx"))
dim(TFs_list)
# Human epifactor and histone gene
Epifactor_list <- read.xlsx(file.path(analysis_dir ,"Epifactor_Histone_list.xlsx"))
dim(Epifactor_list)




# OS_catTFRE_df <- read.delim(file ="data_expression_median.txt", header = T )
OS_catTFRE <- read.xlsx(file.path(analysis_dir ,"catTFRE_Round4_HOS_MG63_U2OS_Thang.xlsx"))
#
# OS_catTFRE_df$Gene_Symbol %>% duplicated() %>% any()
OS_catTFRE[, c(1,38:40)] %>% 
  filter(duplicated(OS_catTFRE$Gene_Symbol)==TRUE) %>% 
  as.data.frame()
# List Gene_Symbol by dplyr::groupby
OS_catTFRE %>% group_by(Gene_Symbol) %>% 
  summarize(frequency = n()) %>% 
  arrange(desc(frequency)) %>% 
  dplyr::filter(frequency > 1) %>% 
  as.data.frame()


# Remove duplicate gene symbol
OS_catTFRE_df <- OS_catTFRE[!duplicated(OS_catTFRE$Gene_Symbol),]
# OS_catTFRE_df <- OS_catTFRE_df[OS_catTFRE_df$Gene_Symbol %in% c(TFs_list$Gene_Symbol, Epifactor_list$HGNC_symbol) ,]
# Add gene Symbol as rownames of metabric data, remove outliner data and change Patient_ID names
# rownames(OS_catTFRE_df) <- OS_catTFRE_df$Gene_Symbol
# Remove colnames without gene expression profile
colnames(OS_catTFRE_df)
# OS_catTFRE_df <- OS_catTFRE_df[,-c(1, 38:40)]
colnames(OS_catTFRE_df)[2:37] <- c(paste(rep("HOS_C1", 4), 1:4, sep="_"), paste(rep("HOS_C4", 4), 1:4, sep="_"), paste(rep("HOS_NE", 4), 1:4, sep="_"),
                             paste(rep("MG63_C1", 4), 1:4, sep="_"), paste(rep("MG63_C4", 4), 1:4, sep="_"), paste(rep("MG63_NE", 4), 1:4, sep="_"),
                             paste(rep("U2OS_C1", 4), 1:4, sep="_"), paste(rep("U2OS_C4", 4), 1:4, sep="_"), paste(rep("U2OS_NE", 4), 1:4, sep="_"))
colnames(OS_catTFRE_df)
head(OS_catTFRE_df)
table(duplicated(OS_catTFRE_df$Gene_Symbol))
table(is.na(OS_catTFRE_df))

```

#Plot overview of data
```{r, Plot overview of data}
str(OS_catTFRE_df)
OS_catTFRE_df[1:2,1:10]
select_column = names(OS_catTFRE_df)[-c(1, 38:40)] # Get all but first  and 38-40 column name

mdata <- OS_catTFRE_df %>%
  tidyr::pivot_longer(., cols = all_of(select_column)) %>%  # Use 'cols' instead of 'col'
  mutate(group = gsub("(_\\d+)$", "", name))  # Remove the trailing underscore and number

# ==== Plot groups (Sample Groups vs RNA Seq Counts) to identify outliers
mdata %>%
    ggplot(., aes(x = name, y = value)) +             # x = catTFRE condition, y = RNA Seq count
    geom_violin() +                                   # violin plot, show distribution
    geom_point(alpha = 0.2) +                         # scatter plot
    theme_bw() +
    geom_point(aes(color = group), alpha = 0.3, size = 1) +  # points also colored
    theme(axis.text.x = element_text(angle = 90) ) +         # Rotate catTFRE condition text 
    labs(x = "catTFRE Groups", y = "MS Spectral Counts") +
    facet_grid(cols = vars(group), drop = TRUE, scales = "free_x")      # Facet by group of catTFRE
ggsave(file=file.path(plots_dir, "OS_MS_sample_spectral_count.pdf"), height = 4, width = 8)
```


```{r}
# We need the input that the rows = treatments and columns = gene probes. then we’re ready to start WGCNA
expr_normalized <- OS_catTFRE_df[, 2:37 ]
rownames(expr_normalized) <- OS_catTFRE_df$Gene_Symbol

input_mat <- t(expr_normalized)
input_mat[1:5, 1:10]
# input_mat <- input_mat[, colnames(input_mat) %in% c(TFs_list$Gene_Symbol, Epifactor_list$HGNC_symbol)]

#library(WGCNA)
allowWGCNAThreads()          # allow multi-threading (optional)
# Allowing multi-threading with up to 4 threads.
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to = 20, by = 2))

# Call the network topology analysis function
sft = pickSoftThreshold(input_mat,             # <= Input data 
                        blockSize = 1000,
                        powerVector = powers,
                        verbose = 5)
par(mfrow = c(1,2));
cex1 = 0.9;
plot(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     xlab = "Soft Threshold (power)",
     ylab = "Scale Free Topology Model Fit, signed R^2",
     main = paste("Scale independence"))
text(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     labels = powers, cex = cex1, col = "red")
# Choose the line of 90%
abline(h = 0.9, col = "red")
plot(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     xlab = "Soft Threshold (power)",
     ylab = "Mean Connectivity",
     type = "n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     labels = powers,
     cex = cex1, col = "red")

```



```{r}
#set.seed(1012)
picked_power = 7
temp_cor <- cor       
cor <- WGCNA::cor         # Force it to use WGCNA cor function (fix a namespace conflict issue)
netwk <- blockwiseModules(input_mat,                # <= input here
                          # == Adjacency Function ==
                          power = picked_power,                # <= power here
                          networkType = "signed",
                          # == Tree and Block Options ==
                          deepSplit = 2,
                          pamRespectsDendro = F,
                          #detectCutHeight = 0.75,
                          minModuleSize = 100,
                          maxBlockSize = 2000,
                          # == Module Adjustments ==
                          reassignThreshold = 0,
                          mergeCutHeight = 0.15,
                          # == TOM == Archive the run results in TOM file (saves time)
                          # loadTOM = T,
                          saveTOMs = T,
                          saveTOMFileBase = "ER",
                          # == Output Options
                          numericLabels = T,
                          verbose = 3)
cor <- temp_cor     # Return cor function to original namespace

# Let’s take a look at the modules, there
# Convert labels to colors for plotting
mergedColors = labels2colors(netwk$colors)
#mergedColors[mergedColors %in% c("red", "magenta")] <- "red"
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(netwk$dendrograms[[1]],
                    mergedColors[netwk$blockGenes[[1]]],
                    "Module colors",
                    dendroLabels = FALSE,
                    hang = 0.03,
                    addGuide = TRUE,
                    guideHang = 0.05 )
# How many gene from each subset
table(netwk$colors)

```


```{r}
library(WGCNA)

# Pick the first block (since you used blockwiseModules, modules are per block)
block1_genes <- netwk$blockGenes[[1]]
block1_dendro <- netwk$dendrograms[[1]]

# Recompute TOM for just that block
dissTOM <- 1 - TOMsimilarityFromExpr(
  input_mat[, block1_genes],
  power = picked_power)

# Plot TOM heatmap with module colors
TOMplot(
  dissTOM,                      # Dissimilarity matrix
  block1_dendro,                # Gene dendrogram
  labels2colors(netwk$colors[block1_genes]),  # Module colors
  main = "Network heatmap (block 1)")
```


# Relate Module (cluster) Assignments to Treatment Groups
```{r}
# netwk$colors[netwk$blockGenes[[1]]]
# table(netwk$colors)

module_df <- data.frame(gene_id = names(netwk$colors),
                        colors = labels2colors(netwk$colors))
head(module_df)
# convert to different arrange
module_wide <- module_df %>%
  group_by(colors) %>%
  mutate(row = row_number()) %>%
  pivot_wider(
    names_from = colors,
    values_from = gene_id) %>%
  dplyr::select(-row)
# write the xlsx file
write.xlsx(module_wide, file.path(plots_dir, "Gene_list_from_each_group_heatmap_12.xlsx"))
# How many gene from each subset with color name
table(module_df$colors)
# which modules are associated with each trait/treatment group. WGCNA will calcuate an Eigangene (hypothetical central gene) for each module, so it easier to determine if modules are associated with different treatments.
# Get Module Eigengenes per cluster
MEs0 <- moduleEigengenes(input_mat, mergedColors)$eigengenes
# Reorder modules so similar modules are next to each other
MEs0 <- orderMEs(MEs0)
module_order = names(MEs0) %>% gsub("ME","", .)
# Add treatment names
MEs0$treatment = row.names(MEs0)

# tidy & plot data
mME = MEs0 %>%
  pivot_longer(-treatment) %>%
  mutate(name = gsub("ME", "", name),
         name = factor(name, levels = module_order)) 

# Replace labels with "color (n)"
levels(mME$name) <- paste0(levels(mME$name),
                           " (", table(module_df$colors)[levels(mME$name)], ")")
# 3. Plot
mME %>% ggplot(aes(x=treatment, y=name, fill=value)) +
  geom_tile() +
  theme_bw() +
  scale_fill_gradient2(low = "blue",
                       high = "red",
                       mid = "white",
                       midpoint = 0,
                       limit = c(-1,1)) +
  theme(axis.text.x = element_text(angle=90, hjust=1),
        legend.position = "bottom",
        legend.direction = "horizontal") +
  labs(title = "Module-trait Relationships",
       y = "Modules (size)", fill="corr")
ggsave(file=file.path(plots_dir, "Module_trait_relationship_catTFRE_WGCNA_MSdata_12.pdf"), height=4, width=7)

```

